services:
  - type: web
    name: safari-ya-maisha
    env: python
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn safari_ya_maisha.wsgi:application
    runtime: python-3.11.9