# Generated by Django 3.2 on 2026-06-08 02:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20260605_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('neno', 'Neno la Mungu'), ('lishe', 'Tiba Lishe'), ('ndoa', 'Mahusiano ya Ndoa')], max_length=20),
        ),
    ]
