# Generated by Django 4.2.30 on 2026-06-09 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_auto_20260607_1903"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("neno", "Neno la Mungu"),
                    ("lishe", "Tiba Lishe"),
                    ("ndoa", "Ushauri Wa Biashara Na Mahusiano ya Ndoa"),
                ],
                max_length=20,
            ),
        ),
    ]
